### ISSUE TITLE
Change addUndirectedEdge()

### ISSUE THREAD

**Issue by ryanjbudhu** [Syzygy05/CS435-Project2#1]
https://github.com/Syzygy05/CS435-Project2/blob/d99a651a202b8d297fbfd376d7ead45aae3e3e42/graph.py#L9-L16

You don't need to add an edge if first and second equal each other, it's an unneeded edge to itself. Consider the case where first is already an edge to second, or vice versa.

**Comment by Syzygy05** [comment]
OK - addressed in https://github.com/Syzygy05/CS435-Project2/commit/2d1c3c294922327949e4437923ed3caa40f13ecd
