### ISSUE TITLE
Adding random connections

### ISSUE THREAD

**Issue by ryanjbudhu** [Syzygy05/CS435-Project2#10]
https://github.com/Syzygy05/CS435-Project2/blob/d99a651a202b8d297fbfd376d7ead45aae3e3e42/main.py#L31-L34

Instead of only creating a hard-coded number of 5 connections, you could use the `random.sample(list, k)` function and run through each node, ensuring that every node is connected to something else.

**Comment by Syzygy05** [comment]
Disagree: If I force the graph to be connected, it would not be random. But I changed the 5 to be a variation of n the parameter entered into the function.
