### ISSUE TITLE
Possible ValueError

### ISSUE THREAD

**Issue by ryanjbudhu** [Syzygy05/CS435-Project2#2]
https://github.com/Syzygy05/CS435-Project2/blob/d99a651a202b8d297fbfd376d7ead45aae3e3e42/graph.py#L19-L20

If second isn't in the list of the first, or vice versa, a `ValueError` will be raised. Consider adding a try...except or using sets and the `Set.discard()` function.

**Comment by Syzygy05** [comment]
OK - addressed in https://github.com/Syzygy05/CS435-Project2/commit/2d1c3c294922327949e4437923ed3caa40f13ecd
