### ISSUE TITLE
Remove this

### ISSUE THREAD

**Issue by ryanjbudhu** [Syzygy05/CS435-Project2#3]
https://github.com/Syzygy05/CS435-Project2/blob/d99a651a202b8d297fbfd376d7ead45aae3e3e42/graph.py#L25-L28

This is not necessary unless the graph is required to be a connected graph.

**Comment by Syzygy05** [comment]
OK addressed in https://github.com/Syzygy05/CS435-Project2/commit/2d1c3c294922327949e4437923ed3caa40f13ecd
