### ISSUE TITLE
Python functionality

### ISSUE THREAD

**Issue by ryanjbudhu** [Syzygy05/CS435-Project2#4]
https://github.com/Syzygy05/CS435-Project2/blob/d99a651a202b8d297fbfd376d7ead45aae3e3e42/graph.py#L23

In Python you are able to iterate through the keys of a dict by default:  
```
newDict = { 'a':1, 'b':2 }
for key in newDict:
    print(key, ':', newDict[key])
```
Evaluates to:  
```
a : 1
b : 2
```

**Comment by Syzygy05** [comment]
Ok addressed in https://github.com/Syzygy05/CS435-Project2/commit/2d1c3c294922327949e4437923ed3caa40f13ecd
