### ISSUE TITLE
Incorrect function signature

### ISSUE THREAD

**Issue by ryanjbudhu** [Syzygy05/CS435-Project2#5]
https://github.com/Syzygy05/CS435-Project2/blob/d99a651a202b8d297fbfd376d7ead45aae3e3e42/graphsearch.py#L8-L11

DFS doesn't need the whole graph, BFT does. DFS should have the function signature: `DFSRec(self, Node: start, Node: end)`

**Comment by Syzygy05** [comment]
Disagree: Python generally ignores function annotations, as long as the user inputs a Node it will work as intended.
