### ISSUE TITLE
Create node ID

### ISSUE THREAD

**Issue by ryanjbudhu** [Syzygy05/CS435-Project2#7]
https://github.com/Syzygy05/CS435-Project2/blob/d99a651a202b8d297fbfd376d7ead45aae3e3e42/main.py#L14-L26

Instead of blindly picking a random number maybe create the numbers and randomize the list. Then run through the randomized list and add each node. As I believe Latka wrote for Sresht:
```
randNums = list(range(n))
random.shuffle(randNums)
```
To create a random list of `n` numbers.

**Comment by Syzygy05** [comment]
Disagree: This is only creating a sequential list of numbers and randomizing the order they appear in the list rather than generating truly random node values.
