### ISSUE TITLE
Keep track of nodes

### ISSUE THREAD

**Issue by ryanjbudhu** [Syzygy05/CS435-Project2#8]
https://github.com/Syzygy05/CS435-Project2/blob/d99a651a202b8d297fbfd376d7ead45aae3e3e42/main.py#L50

You should keep track of the nodes in the `Graph` class not separately. That is what the `Graph.getAllNodes()` function is for.

**Comment by Syzygy05** [comment]
Ok addressed in https://github.com/Syzygy05/CS435-Project2/commit/a957b91ee51b523c6798da43df4ab47af267bd2a
