### ISSUE TITLE
Connecting for LinkedList

### ISSUE THREAD

**Issue by ryanjbudhu** [Syzygy05/CS435-Project2#9]
https://github.com/Syzygy05/CS435-Project2/blob/d99a651a202b8d297fbfd376d7ead45aae3e3e42/main.py#L54

This will only connect a node to the second to last node. A linked-list only connects the first node to the second node, the second node to the third, etc.

**Comment by Syzygy05** [comment]
Disagree: It will connect the second to last node to the node that was just added to the list of nodes. The second to last node is always changing as new nodes are added.
